[project]
name = "ecommerce-lakehouse"
version = "0.1.0"
description = "E-Commerce Lakehouse Architecture on AWS"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.2.3",
]
