[project]
name = "6-ecommerce-lakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.16",
    "openpyxl>=3.1.5",
]
