AWSTemplateFormatVersion: '2010-09-09'
Description: 'E-commerce Lakehouse ETL Pipeline'

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name for the lakehouse
    Default: ecommerce-lakehouse-bucket-123

  GlueJobPrefix:
    Type: String
    Description: Prefix for Glue job names
    Default: ecommerce-lakehouse

  AwsRegion:
    Type: String
    Description: AWS region
    Default: eu-west-1

  GlueDatabasePrefix:
    Type: String
    Description: Prefix for Glue database names
    Default: ecommerce

  ConfigLayerS3Key:
    Type: String
    Description: S3 key for the config layer
    Default: lambda/layers/config_layer.zip

Resources:
  # IAM Role for Lambda functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GlueJobAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:BatchStopJobRun
                Resource: '*'

  # IAM Role for Step Functions
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

  # Config Layer for Lambda functions
  ConfigLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: ecommerce-lakehouse-config
      Description: Layer containing the project configuration
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref ConfigLayerS3Key
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11

  # Bronze Products Lambda
  BronzeProductsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-bronze-products
      Handler: bronze_products_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-bronze-products-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/bronze_products_lambda.zip

  # Bronze Orders Lambda
  BronzeOrdersLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-bronze-orders
      Handler: bronze_orders_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-bronze-orders-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/bronze_orders_lambda.zip

  # Bronze Order Items Lambda
  BronzeOrderItemsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-bronze-order-items
      Handler: bronze_order_items_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-bronze-order-items-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/bronze_order_items_lambda.zip

  # Silver Products Lambda
  SilverProductsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-silver-products
      Handler: silver_products_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-silver-products-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/silver_products_lambda.zip

  # Silver Orders Lambda
  SilverOrdersLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-silver-orders
      Handler: silver_orders_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-silver-orders-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/silver_orders_lambda.zip

  # Silver Order Items Lambda
  SilverOrderItemsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-silver-order-items
      Handler: silver_order_items_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-silver-order-items-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/silver_order_items_lambda.zip

  # Gold Product Performance Lambda
  GoldProductPerformanceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-gold-product-performance
      Handler: gold_product_performance_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-gold-product-performance-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/gold_product_performance_lambda.zip

  # Gold Customer Insights Lambda
  GoldCustomerInsightsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ecommerce-lakehouse-gold-customer-insights
      Handler: gold_customer_insights_lambda.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Layers:
        - !Ref ConfigLayer
      Environment:
        Variables:
          GLUE_JOB_NAME: !Sub "${GlueJobPrefix}-gold-customer-insights-etl"
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AwsRegion
          ECOM_GLUE_DATABASE_PREFIX: !Ref GlueDatabasePrefix
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda/gold_customer_insights_lambda.zip

  # ETL State Machine
  ETLStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: ecommerce-lakehouse-etl-pipeline
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionSubstitutions:
        BronzeProductsLambdaArn: !GetAtt BronzeProductsLambda.Arn
        BronzeOrdersLambdaArn: !GetAtt BronzeOrdersLambda.Arn
        BronzeOrderItemsLambdaArn: !GetAtt BronzeOrderItemsLambda.Arn
        SilverProductsLambdaArn: !GetAtt SilverProductsLambda.Arn
        SilverOrdersLambdaArn: !GetAtt SilverOrdersLambda.Arn
        SilverOrderItemsLambdaArn: !GetAtt SilverOrderItemsLambda.Arn
        GoldProductPerformanceLambdaArn: !GetAtt GoldProductPerformanceLambda.Arn
        GoldCustomerInsightsLambdaArn: !GetAtt GoldCustomerInsightsLambda.Arn
      DefinitionS3Location:
        Bucket: !Ref S3BucketName
        Key: step_functions/etl_state_machine.json

Outputs:
  StateMachineArn:
    Description: ARN of the ETL State Machine
    Value: !Ref ETLStateMachine

  ConfigLayerArn:
    Description: ARN of the Config Layer
    Value: !Ref ConfigLayer
